# Generated by Django 5.2.1 on 2025-05-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('codigo', models.IntegerField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nombre1', models.CharField(db_column='Nombre1', max_length=50)),
                ('nombre2', models.CharField(db_column='Nombre2', max_length=50)),
                ('apellido1', models.CharField(db_column='Apellido1', max_length=50)),
                ('apellido2', models.CharField(db_column='Apellido2', max_length=50)),
                ('tl', models.IntegerField(db_column='TL')),
                ('programa', models.CharField(db_column='Programa', max_length=50)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
    ]
