# Generated by Django 5.2.1 on 2025-07-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univalle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ES', models.CharField(db_column='E/S', max_length=50)),
                ('IP', models.CharField(db_column='Ip_global', max_length=20)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False)),
                ('nombre1', models.CharField(db_column='Nombre1', max_length=50)),
                ('nombre2', models.CharField(blank=True, db_column='Nombre2', max_length=50, null=True)),
                ('apellido1', models.CharField(db_column='Apellido1', max_length=50)),
                ('apellido2', models.CharField(blank=True, db_column='Apellido2', max_length=50, null=True)),
                ('identificacion', models.IntegerField(db_column='Identificacion')),
                ('programa', models.CharField(blank=True, db_column='Programa', max_length=50, null=True)),
                ('foto', models.CharField(db_column='Foto', max_length=50)),
                ('tipo_usuario', models.CharField(db_column='TipoUsuario', max_length=50)),
                ('bandera', models.CharField(db_column='Bandera', max_length=10)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('codigo', models.IntegerField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=128)),
                ('correo', models.CharField(db_column='Correo', max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
